services:
  soketi:
    image: quay.io/soketi/soketi:1.0-16-alpine
    ports:
      - 6001:6001
      - 9601:9601
    restart: always

  coinmatica-telegram:
    build:
      dockerfile: coinmatica-telegram/Dockerfile
      context: .
    environment:
      - PORT=3100
    ports:
      - 3100:3100
    restart: always
