version: "3.9"

services:
  soketi:
    image: quay.io/soketi/soketi:1.0-16-alpine
    ports:
      - 6001:6001
      - 9601:9601
    restart: always

  coinmatica-app:
    build:
      dockerfile: coinmatica-app/Dockerfile
      context: .
      args:
        - COINMATICA_APP_PORT=${COINMATICA_APP_PORT}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
        - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
        - MONGO_USER=${MONGO_USER}
        - MONGO_PASS=${MONGO_PASS}
        - MONGO_DB=${MONGO_DB}
        - MONGO_URL=${MONGO_URL}
        - REDIS_URL=${REDIS_URL}
        - SOKETI_APP_ID=${SOKETI_APP_ID}
        - SOKETI_APP_KEY=${SOKETI_APP_KEY}
        - SOKETI_APP_SECRET=${SOKETI_APP_SECRET}
        - SOKETI_HOST=${SOKETI_HOST}
        - SOKETI_PORT=${SOKETI_PORT}
    environment:
      - COINMATICA_APP_PORT=${COINMATICA_APP_PORT}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_DB=${MONGO_DB}
      - MONGO_URL=${MONGO_URL}
      - REDIS_URL=${REDIS_URL}
      - SOKETI_APP_ID=${SOKETI_APP_ID}
      - SOKETI_APP_KEY=${SOKETI_APP_KEY}
      - SOKETI_APP_SECRET=${SOKETI_APP_SECRET}
      - SOKETI_HOST=${SOKETI_HOST}
      - SOKETI_PORT=${SOKETI_PORT}
    ports:
      - ${COINMATICA_APP_PORT}:${COINMATICA_APP_PORT}
    restart: always

  coinmatica-telegram:
    build:
      dockerfile: coinmatica-telegram/Dockerfile
      context: .
      args:
        - COINMATICA_TELEGRAM_PORT=${COINMATICA_TELEGRAM_PORT}
        - MONGO_USER=${MONGO_USER}
        - MONGO_PASS=${MONGO_PASS}
        - MONGO_DB=${MONGO_DB}
        - MONGO_URL=${MONGO_URL}
        - REDIS_URL=${REDIS_URL}
        - SOKETI_APP_ID=${SOKETI_APP_ID}
        - SOKETI_APP_KEY=${SOKETI_APP_KEY}
        - SOKETI_APP_SECRET=${SOKETI_APP_SECRET}
        - SOKETI_HOST=${SOKETI_HOST}
        - SOKETI_PORT=${SOKETI_PORT}
    environment:
      - COINMATICA_TELEGRAM_PORT=${COINMATICA_TELEGRAM_PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_DB=${MONGO_DB}
      - MONGO_URL=${MONGO_URL}
      - REDIS_URL=${REDIS_URL}
      - SOKETI_APP_ID=${SOKETI_APP_ID}
      - SOKETI_APP_KEY=${SOKETI_APP_KEY}
      - SOKETI_APP_SECRET=${SOKETI_APP_SECRET}
      - SOKETI_HOST=${SOKETI_HOST}
      - SOKETI_PORT=${SOKETI_PORT}
    ports:
      - ${COINMATICA_TELEGRAM_PORT}:${COINMATICA_TELEGRAM_PORT}
    restart: always
