version: "3.9"

services:
  soketi:
    image: quay.io/soketi/soketi:1.0-16-alpine
    ports:
      - 6001:6001
      - 9601:9601
    restart: always

  sematext:
    image: sematext/agent:latest
    environment:
      - INFRA_TOKEN=${SEMATEXT_INFRA_TOKEN}
      - SERVER_BASE_URL=https://spm-receiver.sematext.com
      - LOGS_RECEIVER_URL=https://logsene-receiver.sematext.com
      - EVENT_RECEIVER_URL=https://event-receiver.sematext.com
      - COMMAND_SERVER_URL=https://command.sematext.com
    cap_add:
      - SYS_ADMIN
    restart: always
    volumes:
      - /:/hostfs:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /var/run/:/var/run
      - /sys/kernel/debug:/sys/kernel/debug
      - /sys:/host/sys:ro
      - /dev:/hostfs/dev:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  coinmatica-app:
    build:
      dockerfile: coinmatica-app/Dockerfile
      context: .
      args:
        - COINMATICA_APP_PORT=${COINMATICA_APP_PORT}
        - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
        - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
        - LOGZIO_TOKEN=${LOGZIO_TOKEN}
        - MONGO_USER=${MONGO_USER}
        - MONGO_PASS=${MONGO_PASS}
        - MONGO_DB=${MONGO_DB}
        - MONGO_URL=${MONGO_URL}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - REDIS_URL=${REDIS_URL}
        - SLACK_WEBHOOK_LOGS=${SLACK_WEBHOOK_LOGS}
        - SOKETI_APP_ID=${SOKETI_APP_ID}
        - SOKETI_APP_KEY=${SOKETI_APP_KEY}
        - SOKETI_APP_SECRET=${SOKETI_APP_SECRET}
        - SOKETI_HOST=${SOKETI_HOST}
        - SOKETI_PORT=${SOKETI_PORT}
    environment:
      - COINMATICA_APP_PORT=${COINMATICA_APP_PORT}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - LOGZIO_TOKEN=${LOGZIO_TOKEN}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_DB=${MONGO_DB}
      - MONGO_URL=${MONGO_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - REDIS_URL=${REDIS_URL}
      - SLACK_WEBHOOK_LOGS=${SLACK_WEBHOOK_LOGS}
      - SOKETI_APP_ID=${SOKETI_APP_ID}
      - SOKETI_APP_KEY=${SOKETI_APP_KEY}
      - SOKETI_APP_SECRET=${SOKETI_APP_SECRET}
      - SOKETI_HOST=${SOKETI_HOST}
      - SOKETI_PORT=${SOKETI_PORT}
    ports:
      - 80:${COINMATICA_APP_PORT}
    restart: always

  coinmatica-telegram:
    build:
      dockerfile: coinmatica-telegram/Dockerfile
      context: .
    environment:
      - COINMATICA_TELEGRAM_PORT=${COINMATICA_TELEGRAM_PORT}
      - LOGZIO_TOKEN=${LOGZIO_TOKEN}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_DB=${MONGO_DB}
      - MONGO_URL=${MONGO_URL}
      - REDIS_URL=${REDIS_URL}
      - SLACK_WEBHOOK_LOGS=${SLACK_WEBHOOK_LOGS}
      - SOKETI_APP_ID=${SOKETI_APP_ID}
      - SOKETI_APP_KEY=${SOKETI_APP_KEY}
      - SOKETI_APP_SECRET=${SOKETI_APP_SECRET}
      - SOKETI_HOST=${SOKETI_HOST}
      - SOKETI_PORT=${SOKETI_PORT}
    ports:
      - ${COINMATICA_TELEGRAM_PORT}:${COINMATICA_TELEGRAM_PORT}
    restart: always
