export const TextColor = {
  red: 'text-red-800',
  pink: 'text-pink-800',
  purple: 'text-purple-800',
  ['deep-purple']: 'text-deep-purple-800',
  indigo: 'text-indigo-800',
  blue: 'text-blue-800',
  ['light-blue']: 'text-light-blue-800',
  cyan: 'text-cyan-800',
  teal: 'text-teal-800',
  green: 'text-green-800',
  ['light-green']: 'text-light-green-800',
  lime: 'text-lime-800',
  yellow: 'text-yellow-800',
  amber: 'text-amber-800',
  orange: 'text-orange-800',
  ['deep-orange']: 'text-deep-orange-800',
  brown: 'text-brown-800',
  grey: 'text-grey-800',
  ['blue-grey']: 'text-blue-grey-800',
}

export const BGColor = {
  red: 'bg-red-100',
  pink: 'bg-pink-100',
  purple: 'bg-purple-100',
  ['deep-purple']: 'bg-deep-purple-100',
  indigo: 'bg-indigo-100',
  blue: 'bg-blue-100',
  ['light-blue']: 'bg-light-blue-100',
  cyan: 'bg-cyan-100',
  teal: 'bg-teal-100',
  green: 'bg-green-100',
  ['light-green']: 'bg-light-green-100',
  lime: 'bg-lime-100',
  yellow: 'bg-yellow-100',
  amber: 'bg-amber-100',
  orange: 'bg-orange-100',
  ['deep-orange']: 'bg-deep-orange-100',
  brown: 'bg-brown-100',
  grey: 'bg-grey-100',
  ['blue-grey']: 'bg-blue-grey-100',
}

export type Color = keyof typeof TextColor