name: CI

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
#    env:
#      COINMATICA_APP_PORT: ${{secrets.COINMATICA_APP_PORT}}
#      COINMATICA_TELEGRAM_PORT: ${{secrets.COINMATICA_TELEGRAM_PORT}}
#      DISCORD_CLIENT_ID: ${{secrets.DISCORD_CLIENT_ID}}
#      DISCORD_CLIENT_SECRET: ${{secrets.DISCORD_CLIENT_SECRET}}
#      MONGO_USER: ${{secrets.MONGO_USER}}
#      MONGO_PASS: ${{secrets.MONGO_PASS}}
#      MONGO_DB: ${{secrets.MONGO_DB}}
#      MONGO_URL: ${{secrets.MONGO_URL}}
#      NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
#      NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
#      REDIS_URL: ${{secrets.REDIS_URL}}
#      SOKETI_APP_ID: ${{secrets.SOKETI_APP_ID}}
#      SOKETI_APP_KEY: ${{secrets.SOKETI_APP_KEY}}
#      SOKETI_APP_SECRET: ${{secrets.SOKETI_APP_SECRET}}
#      SOKETI_HOST: ${{secrets.SOKETI_HOST}}
#      SOKETI_PORT: ${{secrets.SOKETI_PORT}}

    steps:
    - uses: actions/checkout@v3
      name: Checkout Repository

#    - name: Set env vars on remote server
#      uses: appleboy/ssh-action@master
#      with:
#        host: ${{ secrets.HETZNER_SSH_HOST }}
#        username: ${{ secrets.HETZNER_SSH_USER }}
#        key: ${{ secrets.HETZNER_SSH_PRIVATE_KEY  }}
#        port: 22
#        script: |
#          grep -q '^COINMATICA_APP_PORT=' /etc/environment && sed -i 's/^COINMATICA_APP_PORT.*/COINMATICA_APP_PORT=$${secrets.COINMATICA_APP_PORT}}/' /etc/environment || echo 'COINMATICA_APP_PORT=$${secrets.COINMATICA_APP_PORT}}' >> /etc/environment
#          grep -q '^COINMATICA_TELEGRAM_PORT=' /etc/environment && sed -i 's/^COINMATICA_TELEGRAM_PORT.*/COINMATICA_TELEGRAM_PORT=$${secrets.COINMATICA_TELEGRAM_PORT}}/' /etc/environment || echo 'COINMATICA_TELEGRAM_PORT=$${secrets.COINMATICA_TELEGRAM_PORT}}' >> /etc/environment

    - uses: alex-ac/github-action-ssh-docker-compose@master
      name: Docker-Compose Remote Deployment
      with:
        ssh_host: ${{secrets.HETZNER_SSH_HOST}}
        ssh_user: ${{secrets.HETZNER_SSH_USER}}
        ssh_private_key: ${{secrets.HETZNER_SSH_PRIVATE_KEY}}
        docker_compose_prefix: coinmatica
        docker_compose_filename: docker-compose.yml
