name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      env:
        HETZNER_SSH_PRIVATE_KEY: ${{secrets.HETZNER_SSH_PRIVATE_KEY}}
      run: |
        echo pk: "${HETZNER_SSH_PRIVATE_KEY}"
        echo host: "${{secrets.HETZNER_SSH_HOST}}"
        echo user: "${{secrets.HETZNER_SSH_USER}}"

    - uses: alex-ac/github-action-ssh-docker-compose@master
      name: Docker-Compose Remote Deployment
      with:
        ssh_private_key: ${{secrets.HETZNER_SSH_PRIVATE_KEY}}
        ssh_host: ${{secrets.HETZNER_SSH_HOST}}
        ssh_user: ${{secrets.HETZNER_SSH_USER}}
        docker_compose_prefix: coinmatica-telegram
        docker_compose_filename: coinmatica-telegram/docker-compose.yml
